spring:
  datasource:
    url: jdbc:mysql://localhost:3306/reading_list
    username: hou8
    password: 100001
    type: com.alibaba.druid.pool.DruidDataSource
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
