spring:
  datasource:
    url: jdbc:mysql://localhost:3306/coral_node
    username: hou8
    password: 100001
    type: com.alibaba.druid.pool.DruidDataSource
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
